### ISSUE TITLE
Chomecast, Chromecast audio, Google Home?

### ISSUE THREAD

**Issue by alexdresko** [dk307/HSPI_ChromecastSpeak#1]
What devices does this speak to? Can it speak to multiple devices? What's the status of this plugin? 

Thanks!

**Comment by dk307** [comment]
I use it with Google Home and Nvidia Shield. It can speak with multiple devices. I have been it  using for 2 months now without any problem. I haven't got to write instructions, but the only additional step is opening web port for chromecast callback. By default it uses 8081 port, but you can override from PlugIn config. There is powershell script in the output to open port in firewall & http driver. You can check opened firewall by  http://<homeseerip>:8081/.

Let me know if it works for you.

Thanks
Deepak

**Comment by alexdresko** [comment]
Works great! I forked the repo, cloned, built in release mode, copied the files out to my HS installation directory, ran the EXE, configured my devices, and confirmed the audio now comes through my google speakers. 

The only thing that caught me off guard was that it doesn't resume whatever I was casting to the speaker before the HS event. Do you think there's a way to resume casting? I doubt it. 

Or do you think there's a way to make speaking to the google devices configurable? Maybe the plugin could expose a device that can be turned on/off? Or maybe it could look for the value of a global variable? I'd like to be able to configure whether or not the plugin speaks to my google devices. There are times when I'm okay with it interrupting my cast (if I'm in the shower, maybe), but there are times when I don't want it doing that (if we're having a lot of people over). 

Also, I thought it was cool that you're using my HomeSeer nuget package. :)

**Comment by dk307** [comment]
Glad it worked.  I earlier looked at resuming the original audio, but it seems to be limitation in the chromecast protocol. Only the device which is casting the audio can control it, so other device which is interrupting cannot resume the old audio/video. But chromecast protocol is evolving, so if you ever find some other app doing this, let me know, I can look into it.

You can control `speak` by creating a virtual device and add it to your events as pre-condition for speaking. That will have similar effect as exposing device from plugin.

And thanks for Homeseer nuget pakage.
