### ISSUE TITLE
Prevents HS from loading

### ISSUE THREAD

**Issue by alexdresko** [dk307/HSPI_ChromecastSpeak#2]
While I mentioned it was working in #1, I just discovered HS won't start after rebooting the computer. It may have worked the first time because I directly launched the plugin EXE while HS was already running.  Upon rebooting, HS failed to launch, and I got several "do you want to debug this" popup windows for a couple HS plugins. 

I can't help but wonder if it's the ilmerge stuff you're doing. As far as I know, the current recommended way to handle DLL dependencies in HS plugins is to put them in their own directory. See the assembly binding section [here](https://github.com/alexdresko/HSPI/blob/59b6e7e223f381cef932069bbf6a3f32432277a6/Templates/HSPIPluginB.Dev/App.config)

I've got my builds configured to automatically get the output in the correct structure. I use [this ps script](https://github.com/alexdresko/HSPI/blob/59b6e7e223f381cef932069bbf6a3f32432277a6/Templates/HSPIPluginB.Dev/fix-output.ps1) in the `AfterBuild` section of my csproj. 

https://github.com/alexdresko/HSPI/blob/59b6e7e223f381cef932069bbf6a3f32432277a6/Templates/HSPIPluginB.Dev/HSPIPluginB.Dev.csproj#L68-L70

If you look at your HS installation directory, you'll probably see several other plugins doing the same thing. 

I'm no expert, though, so take that with a grain of salt.

**Comment by dk307** [comment]
I use several hspi plugins that use ILMerge or Fody Costura to merge assemblies. I have not seen that issue. I fail to see how this hspi plugins can cause other plugin to fail. You can turn off ILMerge and see if problem still persists.
